thisdir = class/System.ComponentModel.DataAnnotations
SUBDIRS =
include ../../build/rules.make

LIBRARY = System.ComponentModel.DataAnnotations.dll
LIB_REFS = System.Core System
LIB_MCS_FLAGS =

TEST_MCS_FLAGS = $(LIB_MCS_FLAGS)

RESX_RESOURCE_STRING = ../../../external/corefx/src/System.ComponentModel.Annotations/src/Resources/Strings.resx

include ../../build/library.make
